version: "3.5"

services:
  cron:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  listener:
    image: ghcr.io/hueske-digital/cronjobs:latest
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/main.py:/app/main.py
    environment:
      - PYTHONUNBUFFERED=1
